### ISSUE TITLE
How to use this warehouse with LVGL?

### ISSUE THREAD

**Issue by modi12jin** [nopnop2002/esp-idf-parallel-tft#15]
I am a novice and want to use LVGL, but I don't know how to use it together. Hope to add some clarification

**Comment by nopnop2002** [comment]
Unfortunately I have never used LVGL.

However, as far as we can see here, LVGL does not support parallel TFTs.

https://github.com/lvgl/lvgl_esp32_drivers

https://github.com/lvgl/lvgl_esp32_drivers#supported-display-controllers

**Comment by modi12jin** [comment]
@nopnop2002 

https://github.com/espressif/esp-iot-solution/issues/122

I got the information about using LVGL on parallel port at Espressif's official components
