### ISSUE TITLE
Add ST7789 support

### ISSUE THREAD

**Issue by modi12jin** [nopnop2002/esp-idf-parallel-tft#19]
![ST7789-FT5336](https://user-images.githubusercontent.com/40233017/134374752-54e478cb-c199-46da-a04f-5d2c158eec7f.jpg)

![ST7789](https://user-images.githubusercontent.com/40233017/134374952-a9943c40-bf97-4299-b174-57372841c071.jpg)

![20210922234012](https://user-images.githubusercontent.com/40233017/134375954-36dd0ca0-cd3b-4b59-9ceb-00a00cb5a70f.jpg)

> I bought the ST7789 parallel port 8-bit screen on Taobao or AliExpress, and it was successfully lit.

https://user-images.githubusercontent.com/40233017/134378077-3bf54008-d855-4e2b-ab9c-f8909773ea83.mp4

![20210922234549](https://user-images.githubusercontent.com/40233017/134377745-99acdecd-a531-40c7-91af-d87c58aa09d8.jpg)

>  This is my attempt on ESP32S2

> My code comes from the official warehouse of Espressif which supports ST7789. I believe yours should also support it. I hope you can transplant it.

![20210923001431](https://user-images.githubusercontent.com/40233017/134382086-a3679689-b71f-4af0-9faa-d026a818f01f.jpg)

![20210923001722](https://user-images.githubusercontent.com/40233017/134382489-20953ba5-30fd-48ac-9604-581b31c8d670.jpg)

![20210923001934](https://user-images.githubusercontent.com/40233017/134382741-9a535bbc-a6bc-4fed-b834-5861ea8f2116.jpg)

https://github.com/espressif/esp-iot-solution

**Comment by modi12jin** [comment]
> If someone wants to use this screen, they need to pay attention to the screen interface and backlight voltage

![20210923002738](https://user-images.githubusercontent.com/40233017/134383931-fed03583-40d3-4929-b76f-ccd7cc78ceea.jpg)

![20210923003220](https://user-images.githubusercontent.com/40233017/134384585-8327b188-d69e-4943-8bdf-7022bcdb801c.jpg)

**Comment by nopnop2002** [comment]
I found this on AliExpress.

Can I buy this converted PCB on AliExpress?

![st7789](https://user-images.githubusercontent.com/6020549/134427635-941e9c27-49dc-4f1f-8cc7-d541cbb6d77a.jpg)

**Comment by modi12jin** [comment]
> I drew the screen adapter board by myself, but it did not solve the backlight problem. I used a boost module, and it is better to use a backlight chip because of the constant current.

![He932264ba53c410999b14644ead15abaj](https://user-images.githubusercontent.com/40233017/134448309-b3f157ce-19dc-4f59-8d0b-755483585018.jpg)

![google-chrome_20210923105107](https://user-images.githubusercontent.com/40233017/134448355-0b7f9798-fd94-4bd9-9164-87335b547770.jpg)

DD1718PA with pins 3-18V turn to positive and negative 5V 6V 9V 12V 15V 24V DC Step Up Boost Converter Power Supply Module

> Screen interface adapter board

![lceda_20210923105646](https://user-images.githubusercontent.com/40233017/134448586-a0abe347-8f38-4502-a953-280ab199f191.jpg)

![lceda_20210923105744](https://user-images.githubusercontent.com/40233017/134448650-abd2a519-30a4-4cec-a06a-79582a2f161d.jpg)

![lceda_20210923105931](https://user-images.githubusercontent.com/40233017/134448770-1a2c3f86-bfa7-4598-8cb4-3f5d5739c00c.jpg)

![20210923110729](https://user-images.githubusercontent.com/40233017/134449331-aa321b52-3204-4ff5-b8bc-44476a5d5902.jpg)

> lceda screen interface adapter board project

[Project_AXT524124转接板_2021-09-23_11-13-02.zip](https://github.com/nopnop2002/esp-idf-parallel-tft/files/7214849/Project_AXT524124._2021-09-23_11-13-02.zip)

> Touch adapter board can be bought ready-made

![google-chrome_20210923112304](https://user-images.githubusercontent.com/40233017/134450352-4978e2f1-2416-40af-8769-2ce4359bfd3a.jpg)

**Comment by nopnop2002** [comment]
Thank you for information.

**Comment by modi12jin** [comment]
# 1_Screen ST7789V (8080 parallel port 8-bit) pin connection relationship with ESP32-S2 pin

| ST7789V pin number |     LCD function    | ESP32-S2 pin |
| :-------------: | :--------------: | :----------: |
|        1        |       BL_K       |     GND      |
|        2        |       BL_A       |     15V      |
|        3        |       GND        |     GND      |
|        4        | IOVCC(1.8V/2.8V) |     3.3V     |
|        5        |    VDD(2.8V)     |     3.3V     |
|        6        |       GND        |     GND      |
|        7        |       /CS        |     GND      |
|        8        |      /RSTB       |     3.3V     |
|        9        |        RS        |    GPIO41    |
|       10        |       WRB        |    GPIO40    |
|       11        |       RDB        |     3.3V     |
|       12        |       DB7        |    GPIO7     |
|       13        |       DB6        |    GPIO6     |
|       14        |       DB5        |    GPIO5     |
|       15        |       DB4        |    GPIO4     |
|       16        |       DB3        |    GPIO3     |
|       17        |       DB2        |    GPIO2     |
|       18        |       DB1        |    GPIO1     |
|       19        |       DB0        |    GPIO0     |
|       20        |        TE        |     Hang in the air     |
|       21        |        NC        |     Hang in the air     |
|       22        |        NC        |     Hang in the air     |
|       23        |        NC        |     Hang in the air     |
|       24        |        NC        |     Hang in the air     |


# 2_Touch FT5336 pin and ESP32-S2 pin connection relationship

| FT5336 pin number |  touch function  | ESP32-S2 pin |
| :------------: | :---------: | :----------: |
|       1        |     GND     |     GND      |
|       2        |  INT(1.8V)  |     Hang in the air      |
|       3        |     GND     |     GND      |
|       4        |  SDA(1.8V)  |    GPIO8     |
|       5        |  SCL(1.8V)  |    GPIO9     |
|       6        | RESET(1.8V) |     3.3V     |
|       7        |  VDD(2.8V)  |     3.3V     |
|       8        |     GND     |     GND      |

**Comment by nopnop2002** [comment]
Perhaps ST7789 and ILI9341 have the same control code.

Try with ILI9341.
