### ISSUE TITLE
QUESTION: open-smart ILI9320 not support

### ISSUE THREAD

**Issue by chaoshendasixiong** [nopnop2002/esp-idf-parallel-tft#20]
i got a [tft lcd ili9320](https://michiel.vanderwulp.be/domotica/Modules/OpenSmartStore-LCD/)
and Wemos D1 ESP32, i have changed RS CS RST pins from 35,34,36 to 15,33,32
menuconfig select 9320, but is doesn't work, always white.
Is it not suitable for OPEN-SMART Products? should i giveup to use another lcd or any recommend driver type?

**Comment by nopnop2002** [comment]
I don’t have open-smart ILI9320 2.8 inch TFT.

I2S parallel may not work for OPEN-SMART Products.

Try changing the interface to GPIO parallel.

__OPEN-SMART Products have different pin arrangements from general TFT shields.__
__You have to change GPIO assign.__

![107723948-ff565e80-6d25-11eb-89cc-74fcd2fa11f3](https://user-images.githubusercontent.com/6020549/143344163-9bc8dfb9-5c64-4fe1-85fb-7a07bd73960f.jpg)


![107725257-2e220400-6d29-11eb-808a-a440336780d6](https://user-images.githubusercontent.com/6020549/143333997-d67435b7-a194-42f3-b589-87c79a039ba7.jpg)


![ili9320](https://user-images.githubusercontent.com/6020549/143334284-24a09768-aa72-469d-8c89-f89ba665b0a2.jpg)

![gpio](https://user-images.githubusercontent.com/6020549/143334578-8d42a4b3-80a0-4cd2-adbe-509a0b9237df.jpg)

**Comment by chaoshendasixiong** [comment]
oh, i got it, thank u so very much!!!
i just was confused by the silk screen of back borad, the meaning of DB2,3,5 is LCD_D2,LCD_D3, LCD_D5. 
now it's work normal.
