### ISSUE TITLE
ESP IDF Component Manager

### ISSUE THREAD

**Issue by modi12jin** [nopnop2002/esp-idf-parallel-tft#22]
When can I see this item in the Component Manager registry?

**Comment by nopnop2002** [comment]
ESP-IDF is currently in transition from V4.4 to V5.0.

These are very different.

Especially decoding JPEG requires a completely different code.

We are working to support both V4.4 and V5.0.

The Component Manager registry is useful, but good for a single version.
The Component Manager registry is not suitable for multiple versions.

**Comment by modi12jin** [comment]
@nopnop2002  https://github.com/espressif/idf-extra-components/issues/106

 The official jpeg decoding supports SIMD, but it just takes time.  If done this will be the best performing jpeg codec

 V5 version has been released, I believe your driver will be useful for those who use LVGL.  But I hope your code will be similar to the official template.

**Comment by nopnop2002** [comment]
I may not have understood your comment correctly.

Here's my current JPEG decoding implementation:

There are too many differences between V4 and V5, the source files are different.



For ESP-IDF V4.4
- ESP32:Using ROM Library
- ESP32S2:Not available
- ESP32S3:Using ROM Library
- ESP32H2:Not supported
- ESP32C2:Not supported
- ESP32C3:Using ROM Library

For ESP-IDF V5.x
With ESP-IDF Ver5, the JPEG decode library is now provided from the IDF Component Registry.
Some SoCs can take advantage of this.
- ESP32:Using ROM Library(Don't work IDF Component Registry)
- ESP32S2:Using IDF Component Registry
- ESP32S3:Using ROM Library(Don't work IDF Component Registry)
- ESP32H2:Using ROM Library(Don't work IDF Component Registry)
- ESP32C2:Using IDF Component Registry
- ESP32C3:Using ROM Library(Don't work IDF Component Registry)

**Comment by modi12jin** [comment]
Thank you so much for your patience!
