### ISSUE TITLE
Add support for R61529

### ISSUE THREAD

**Issue by modi12jin** [nopnop2002/esp-idf-parallel-tft#23]
![2022-03-13 11-36-27屏幕截图](https://user-images.githubusercontent.com/40233017/158043928-923c7c3e-0fb4-4717-8e69-a0274a3db028.png)

```
https://github.com/JadedTuna/lcd-dma-issue
```

![2022-03-13 11-38-31屏幕截图](https://user-images.githubusercontent.com/40233017/158043982-4818b0b1-9827-4ea8-ae5d-5607198364cf.png)

```
https://github.com/espressif/esp-idf/issues/8085
```

![2022-03-13 11-33-22屏幕截图](https://user-images.githubusercontent.com/40233017/158043847-a3ad9c03-d9ab-4bd7-a3d8-dda9114f54bd.png)

```
https://github.com/daumemo/IPS_LCD_R61529_FT6236_Arduino_eSPI_Test
```

![2022-03-13 11-40-49屏幕截图](https://user-images.githubusercontent.com/40233017/158044039-f00244c2-48c0-4092-a5a1-1042c951d38c.png)

```
https://github.com/moononournation/Arduino_GFX
```

@nopnop2002 Hello, I wonder if you have any plans for R61529 support?

**Comment by modi12jin** [comment]
![2022-03-13 11-47-18屏幕截图](https://user-images.githubusercontent.com/40233017/158044209-03dbe61a-6afe-4fbc-bc06-4d5d596e2877.png)

[Buy on Aliexpress](https://www.aliexpress.com/item/32940608152.html?spm=a2g0o.productlist.0.0.66e773f6vAhLCI&algo_pvid=f9214500-0ba3-4aff-b9a8-9fc9dc51cd2a&algo_expid=f9214500-0ba3-4aff-b9a8-9fc9dc51cd2a-16&btsid=25887317-95e8-4f7a-aabc-1913fdfeaadf&ws_ab_test=searchweb0_0,searchweb201602_6,searchweb201603_53)

**Comment by modi12jin** [comment]
![2022-03-13 11-52-34屏幕截图](https://user-images.githubusercontent.com/40233017/158044349-267041e8-82ee-4446-8954-a9d4d148d102.png)

```
https://daumemo.com/ips-capacitive-lcd-on-an-esp32-diy-generator-part-8/
```

According to the seller, the LCD has IPS panel, which has great viewing angles. Also, it has resolution of 480×320 which might be a bit of a problem when used with not so powerful MCU such as ESP32. It has 8080 (MIPI-DBI Type B) interface for sending image data to the LCD. It also should have an SPI connection, but I haven’t tried it, and what is more, according to the LCD driver’s datasheet, it doesn’t support sending image data through the SPI (only commands for setting up the display).

As mentioned in the description it can be interfaced by 8 or 16 data bit lanes and because ESP32 has a few available pins, 8-bit interface was used. Through this interface you can send 16, 18 or 24 bits per pixel which means that you can get up to 16M of colors from this LCD (provided you have enough of the MCU resources).

![2022-03-13 11-57-19屏幕截图](https://user-images.githubusercontent.com/40233017/158044438-e3de887e-839f-4ff3-8678-a3f47a6c09dd.png)

@nopnop2002 this might help

**Comment by modi12jin** [comment]
![6232_1647146183_hd](https://user-images.githubusercontent.com/40233017/158045264-b7009af6-fe2e-4241-ab26-b1e8d41e0486.jpeg)

[LiangHaoCai-3.5 inch IPS-40p-R61529A-data package.zip](https://github.com/nopnop2002/esp-idf-parallel-tft/files/8238978/LiangHaoCai-3.5.inch.IPS-40p-R61529A-data.package.zip)

@nopnop2002 China Taobao store, the information given by the seller.

**Comment by nopnop2002** [comment]
I can't find "TFT Shield" that using R61529.

The product you have shown is not common.

**Comment by modi12jin** [comment]
@nopnop2002 This screen can be purchased at Buy on Aliexpress

https://es.aliexpress.com/item/32940608152.html?gatewayAdapt=glo2esp&spm=a2g0o.productlist.0.0.66e773f6vAhLCI&algo_pvid=f9214500-0ba3-4aff-b9a8-9fc9dc51cd2a&algo_expid=f9214500-0ba3-4aff-b9a8-9fc9dc51cd2a-16&btsid=25887317-95e8-4f7a-aabc-1913fdfeaadf&ws_ab_test=searchweb0_0,searchweb201602_6,searchweb201603_53

![2022-03-13 18-30-23屏幕截图](https://user-images.githubusercontent.com/40233017/158055442-eb878688-d1ee-49fb-8dae-2b2702a77806.png)

![2022-03-13 18-34-24屏幕截图](https://user-images.githubusercontent.com/40233017/158055573-580fca40-84a9-4bf1-97f6-b9d563d02697.png)

[LiangHaoCai-3.5寸IPS-40p-R61529A.pdf](https://github.com/nopnop2002/esp-idf-parallel-tft/files/8239354/LiangHaoCai-3.5.IPS-40p-R61529A.pdf)

![2022-03-13 18-38-30屏幕截图](https://user-images.githubusercontent.com/40233017/158055666-62c64914-18b8-4c6c-92c6-f66d7c291b1b.png)

[R61529_DS_V0.00.pdf](https://github.com/nopnop2002/esp-idf-parallel-tft/files/8239361/R61529_DS_V0.00.pdf)

**Comment by modi12jin** [comment]
https://github.com/daumemo/IPS_LCD_R61529_FT6236_Arduino_eSPI_Test/issues/1

![2022-03-13 19-25-31屏幕截图](https://user-images.githubusercontent.com/40233017/158057190-61168c55-15d6-4130-baf6-357cfddc75e3.png)

@nopnop2002 Compatibility may exist

**Comment by modi12jin** [comment]
@nopnop2002 My friend tested it and there is compatibility. Thank you

https://user-images.githubusercontent.com/40233017/158057732-97f95da4-c6e3-401c-ad92-a98d9e47b792.mp4
