### ISSUE TITLE
Support for ESP32S3

### ISSUE THREAD

**Issue by modi12jin** [nopnop2002/esp-idf-parallel-tft#24]
@nopnop2002 Hi, are there plans for ESP32S3 support?

**Comment by nopnop2002** [comment]
Yes,
I will support when i get it.

But it's still expensive.

**Comment by NIDA11120204** [comment]
hi, I can send you free samples~

**Comment by nopnop2002** [comment]
Currently, ESP-IDF is in the process of migrating to Ver5.

S3 support and Ver5 support should be considered separately.

ESP-IDF Ver5 is very buggy.

The transition to Ver5 is very dangerous.

Therefore, I will support ESP32-S3 with Ver4.4 in the near future.

When ESP-IDF Ver5 becomes stable, we will release the corresponding version again.

**Comment by NIDA11120204** [comment]
> Yes, I will support when i get it.
> 
> But it's still expensive.

Could you support for Ai-Thinker ESP-S3-12K and ESP-S3-32S? I can send you the samples

**Comment by nopnop2002** [comment]
Ai-Thinker ESP-S3-12K will arrive in the near future.

Support for Ver5 If not included, welcome your sample.

**Comment by NIDA11120204** [comment]
> 

may I have your contact?

**Comment by NIDA11120204** [comment]
> Ai-Thinker ESP-S3-12K will arrive in the near future.
> 
> Support for Ver5 If not included, welcome your sample.

may I have your contact?

**Comment by nopnop2002** [comment]
Unfortunately, I don't publish my email address.



You can publish your sample using your repository

**Comment by NIDA11120204** [comment]
> Unfortunately, I don't publish my email address.
> 
> You can publish your sample using your repository

Could you give me your email right now and delete in 2 minutes?

**Comment by nopnop2002** [comment]
hau26280@tree.odn.ne.jp

**Comment by nopnop2002** [comment]
hau26280@tree.odn.ne.jp

**Comment by nopnop2002** [comment]
I give you my email address and delete in 2 minutes

**Comment by NIDA11120204** [comment]
> I give you my email address and delete in 2 minutes

you can delete now

**Comment by nopnop2002** [comment]
i2s_lcd_esp32s3_driver.c does not exist yet in [here](https://github.com/espressif/esp-iot-solution/tree/master/components/bus).

**Comment by nopnop2002** [comment]
Added support for ESP32S3. 

---

I can't find the pinmap image for Ai-Thinker ESP-S3-12K anywhere.

**Comment by modi12jin** [comment]
@nopnop2002 Since there is some friction between Espressif and Espressif, your board may become a legacy, they are no longer in production

**Comment by modi12jin** [comment]
@nopnop2002 They are no longer producing esp32s3, and there is friction with Espressif (maybe because of proxying other MCUs with WiFi)

**Comment by modi12jin** [comment]
@nopnop2002 They are no longer making the esp32s3, so your board may become legacy.

**Comment by modi12jin** [comment]
@nopnop2002 ESP-S3-12K does not need too much introduction. It should be noted that both flash and psram are QSPI, and both are 8MB.
