### ISSUE TITLE
How to connect ESP-32 

### ISSUE THREAD

**Issue by oneandonlyonebutyou** [nopnop2002/esp-idf-parallel-tft#26]
Thank you for working on such an important project, 
I am very new to displays and ESP-32, Could you please help me to connect my display and run a simple test 
<img width="666" alt="image" src="https://user-images.githubusercontent.com/17168374/167986830-606485f9-c8c5-4b59-8709-3ad57f48a923.png">

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/17168374/167986900-6291667d-ad7a-4441-962e-4ce327997310.png">
and my board :

<img width="2062" alt="image" src="https://user-images.githubusercontent.com/17168374/167987455-481e78b0-2632-4f74-9097-eed2eafffb5a.png">

Thank you so much

**Comment by nopnop2002** [comment]
# Wireing  

|TFT||ESP32|ESP32S2/S3||
|:-:|:-:|:-:|:-:|:-:|
|LDC_RST|--|GPIO32|GPIO45|*1|
|LDC_CS|--|GPIO33|GPIO42|*1|
|LDC_RS|--|GPIO15|GPIO41|*1|
|LDC_WR|--|GPIO4|GPIO40|*1|
|LDC_RD|--|GPIO2|GPIO39|*1|
|LDC_D0|--|GPIO12|GPIO1|*1 *2|
|LDC_D1|--|GPIO13|GPIO2|*1 *2|
|LDC_D2|--|GPIO26|GPIO3|*1 *2|
|LDC_D3|--|GPIO25|GPIO4|*1 *2|
|LDC_D4|--|GPIO17|GPIO5|*1 *2|
|LDC_D5|--|GPIO16|GPIO6|*1 *2|
|LDC_D6|--|GPIO27|GPIO7|*1 *2|
|LDC_D7|--|GPIO14|GPIO8|*1 *2|
|5V|--|5V|5V|*3|
|3.3V|--|3.3V|3.3V|*3|
|GND|--|GND|GND||

(*1)   
You can change any GPIO using menuconfig.   

![config-app3](https://user-images.githubusercontent.com/6020549/106685441-be669780-660b-11eb-8e8e-790348e65921.jpg)

(*2)   
When using REGISTER I/O parallel, GPIO from D0 to D7 is 1 to 31.(GPIO0 is boot mode pin)   

(*3)   
With a regulator (mostly AMS1117) is on the back, the supply voltage is 5V.   
With a regulator is NOT on the back, the supply voltage is 3.3V.

**Comment by oneandonlyonebutyou** [comment]
Since I don’t have any other external devices attached, I would be happy with the default one. 
Could you kindly share some example for text and some animations ( like fire or wind ) 

really appreciate it

**Comment by nopnop2002** [comment]
https://www.youtube.com/watch?v=D90OSlKYpfA

There is a lot of video on the WEB.

Search "esp32 tft"

Serach "esp-idf example"

**Comment by oneandonlyonebutyou** [comment]
Thank you so much .
