### ISSUE TITLE
[GIF IMAGE FOR TFT SCREEN]

### ISSUE THREAD

**Issue by quoctrung99** [nopnop2002/esp-idf-parallel-tft#30]
Can you tell me how to display gif on tft screen?

**Comment by nopnop2002** [comment]
>gif on tft screen?

I only know how to view png and jpeg.


If you google it you will find the gif format.


Here is gif decorder library.
I'm sure there are many other C language libraries that decode GIFs.

https://blog.boochow.com/article/428487132.html
