### ISSUE TITLE
[ILI9806E SUPPORT?]

### ISSUE THREAD

**Issue by quoctrung99** [nopnop2002/esp-idf-parallel-tft#31]
When using driver ili9806 just change ???
![image](https://user-images.githubusercontent.com/81129543/229084209-5ff4adc7-9fee-4501-94f8-84dbd7778057.png)

![image](https://user-images.githubusercontent.com/81129543/229084428-5785b13b-cca5-453c-87d8-4d472b68e0f7.png)
 I using i2s 16 bit parallel

**Comment by nopnop2002** [comment]
>I using i2s 16 bit parallel

This project don't support 16 bit parallel tft.


It doesn't work even if you change the initialization code of TFT.
