### ISSUE TITLE
How can i add the TFT configuration to menuconfig in a scratch project ? 

### ISSUE THREAD

**Issue by cesar-solis** [nopnop2002/esp-idf-parallel-tft#32]
I'm new at using the idf.py commands, i always use de GUI options from VSC through ESP-IDF extension, i want to use all functions to create a nice GUI but how can i add the config to menuconfig ?

**Comment by nopnop2002** [comment]
I don't use VSC so I don't know.

Please search on Google.

I find VSC more difficult than command line.

The command line is just typing 5 commands.

**Comment by cesar-solis** [comment]
i'm using ubuntu now, so what should i do to add the config in menuconfig ?. Just gitclone to a components file ?

**Comment by nopnop2002** [comment]
```
git clone https://github.com/nopnop2002/esp-idf-parallel-tft
cd esp-idf-parallel-tft/
idf.py set-target {esp32/esp32s2/esp32s3}
idf.py menuconfig
idf.py flash
```

More detail is here.
https://docs.ai-thinker.com/en/esp32/docs/esp32_idf_menuconfig
