### ISSUE TITLE
usb camera  with lcd 

### ISSUE THREAD

**Issue by Nadeemranm** [nopnop2002/esp-idf-parallel-tft#33]
Can i use for the usb camera live streaming on  8 bit parallel line interface ili9486 lcd 
which function will be use for the live streaming of this library ?

**Comment by nopnop2002** [comment]
JPEG display is slow, so live streaming display is impossible.

A display speed of about 15 FPS is required for live streaming.

This display speed is impossible with ESP32.

It is possible if it is about 1 FPS.

It is necessary to create a new MPEG reception function.

**Comment by Nadeemranm** [comment]
I have this lcd ,
It's  possible live streaming on this lcd using lovyanGFX library ?

Thank you

**Comment by nopnop2002** [comment]
I don't know the lovyanGFX library so I can't answer.

**Comment by Nadeemranm** [comment]
I have your github file ,and i want to usb camera live streaming on 8 bit
parallel line interface ILI9486 lcd ,
in code where  i should have to be change ?
how to create bitmap function for live streaming on lcd

**Comment by nopnop2002** [comment]
USB-CAMERA outputs MPEG (=JPEG).

USB-CAMERA--->JPEG---(HTTP)-->ESP32--->8 bit parallel line interface.

>in code where  i should have to be change ?

You have to write a lot of new code.

A display speed of about 15 FPS is required for live streaming.

However, with the CPU power of ESP32, 1 FPS is the limit.

JPEG display on SPIFFS is here.
https://github.com/nopnop2002/esp-idf-parallel-tft/blob/main/main/main.c#L840
