### ISSUE TITLE
0xFFFF White color appears to be mint green on ILI9486

### ISSUE THREAD

**Issue by Jalxie** [nopnop2002/esp-idf-parallel-tft#6]
# Enviroment 
- Development Kit: ESP32-DevKitC
- Kit version: v4
- Module or chip used: ESP32-WROOM-32D
- IDF version: ESP-IDF v4.1 5ef1b3900 
- Build System: CMake
- Operating System: Windows 10 Pro 19042.746
- Power Supply: USB

# Problem Description
On [3.5inch Arduino Display-UNO](http://www.lcdwiki.com/3.5inch_Arduino_Display-UNO), the color 0xFFFF appears to be mint green. 
![微信图片_20210203140122](https://user-images.githubusercontent.com/29851748/106692194-612d0f00-6628-11eb-9e3e-7bfa33ff8588.jpg)
![微信图片_20210203140129](https://user-images.githubusercontent.com/29851748/106692224-638f6900-6628-11eb-89b3-2fad3801dae3.jpg)
![微信图片_20210203140132](https://user-images.githubusercontent.com/29851748/106692247-64c09600-6628-11eb-9f0d-a010c1bd56a3.jpg)
![微信图片_20210203140135](https://user-images.githubusercontent.com/29851748/106692265-65f1c300-6628-11eb-8f8e-53dfcbf19a7f.jpg)
![微信图片_20210203140139](https://user-images.githubusercontent.com/29851748/106692289-67bb8680-6628-11eb-8744-6915a7f846e1.jpg)

- The screen uses ILI9486 driver.
- Default Pin configuration

**Comment by nopnop2002** [comment]
Is the RGB color bar displayed correctly?

And please tell me [this result](https://github.com/prenticedavid/MCUFRIEND_kbv/tree/master/examples/LCD_ID_readreg)

![Graphic2](https://user-images.githubusercontent.com/6020549/104248263-85c01c00-54ac-11eb-9d19-6886827cd29d.JPG)

**Comment by Jalxie** [comment]
Yes. 
![微信图片_20210203165611](https://user-images.githubusercontent.com/29851748/106704814-d60c4300-6640-11eb-9b42-0c927ecb9783.jpg)

**Comment by nopnop2002** [comment]
Please tell me this result:

https://github.com/prenticedavid/MCUFRIEND_kbv/tree/master/examples/LCD_ID_readreg

**Comment by Jalxie** [comment]
Sorry, could you please explain a little bit?  Run the code on ESP32?

**Comment by nopnop2002** [comment]
no.
This is for Arduno UNO.

Maybe your TFT is not LI9486.
It becomes clear if you read the register of TFT.

**Comment by Jalxie** [comment]
Ok, got it. But don't have an Arduino at the moment.  

I'll see if I can get one.

Thanks.

**Comment by nopnop2002** [comment]
Do not use this on the ESP32 as the GPIO on the ESP32 is not 5V tolerant.
